apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: loadtest
    name: loadtest
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: loadtest
    strategy: {}
    template:
      metadata:
        labels:
          app: loadtest
      spec:
        containers:
        - image: nakanakau/loadtest:latest
          name: loadtest
          resources:
            requests:
              cpu: "25m"
              memory: 25Mi
            limits:
              cpu: "100m"
              memory: 100Mi

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: loadtest
    name: loadtest
  spec:
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: loadtest
kind: List
metadata: {}
